---
- hosts: localhost
  tasks:
    - include_vars: input_vars.yml
    - name: create a cloudformation stack
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: "present"
        region: "{{ region }}"
        disable_rollback: true
        template: "Files/sagemaker.json"
        template_parameters:
          NotebookInstanceName: "{{ NotebookInstanceName }}"
          NotebookInstanceType: "{{ NotebookInstanceType }}"
          SageMakerRoleArn: "{{ SageMakerRoleArn }}"
          EBSVolumeSize: "{{ EBSVolumeSize }}"
        tags:
          Stack: "{{ stack_name }}"